# Create dataset: Highest vs rest (high, medium, low, lowest)
* Under sampling the majority class.
* 50/50 balance per class.

In [2]:
import pandas as pd
# Import csv file
df = pd.read_csv('../../csv/jira_clean_with_all_cols.csv')
df

,priority,description,project,labels,issuetype,collection,class,text_str,text_clean
0,Blocker,We tried upgrading from Spring Boot 2.0.6 to S...,Spring XD,[],Bug,Spring,Highest,We tried upgrading from Spring Boot 2.0.6 to S...,we tried upgrading from spring boot to spring ...
1,Major,The jobs that appear under Executions section ...,Spring XD,[],Bug,Spring,Medium,The jobs that appear under Executions section ...,the jobs that appear under executions section ...
2,Trivial,Working with Spring-XD version 1.3.2.RELEASE\n...,Spring XD,[],Bug,Spring,Lowest,Working with Spring-XD version 1.3.2.RELEASE\n...,working with springxd version the server with ...
3,Major,My project 7 node cluster and in that 2 node a...,Spring XD,"['Spring', 'xd']",Bug,Spring,Medium,My project 7 node cluster and in that 2 node a...,my project node cluster and in that node are a...
4,Minor,See https://github.com/spring-projects/spring-...,Spring XD,[],Story,Spring,Low,See https://github.com/spring-projects/spring-...,NaN
...,...,...,...,...,...,...,...,...,...
1404240,Major,it is very beautiful.,Community Support - Open Source Project Reposi...,[],New Project,Sonatype,Medium,it is very beautiful.,it is very beautiful
1404241,Major,library,Community Support - Open Source Project Reposi...,[],New Project,Sonatype,Medium,library,NaN
1404242,Major,What is reactive-gremlin\r\n\r\nreactive-greml...,Community Support - Open Source Project Reposi...,[],New Project,Sonatype,Medium,What is reactive-gremlin\r\n\r\nreactive-greml...,what is reactivegremlin reactivegremlin is a s...
1404243,Major,"Android view for a swipeable, weekly calendar.",Community Support - Open Source Project Reposi...,[],New Project,Sonatype,Medium,"Android view for a swipeable, weekly calendar.",android view for a swipeable weekly calendar
1404244,Major,"Beetlmvc is a web framework, which can support...",Community Support - Open Source Project Reposi...,[],New Project,Sonatype,Medium,"Beetlmvc is a web framework, which can support...",beetlmvc is a web framework which can support ...

In [3]:
# Count class
df['class'].value_counts().to_frame()

          count
class
Medium   960459
Low      271629
High      82646
Highest   56220
Lowest    33291

In [4]:
# NaN values
df.isnull().sum()

priority           0
description        0
project            0
labels             0
issuetype          0
collection         0
class              0
text_str           0
text_clean     34264
dtype: int64

In [5]:
# Count class
df['class'].value_counts().to_frame()

          count
class
Medium   960459
Low      271629
High      82646
Highest   56220
Lowest    33291

In [6]:
# Unique collections
df['collection'].unique()

array(['Spring', 'RedHat', 'Sakai', 'JiraEcosystem', 'Hyperledger',
       'Apache', 'SecondLife', 'IntelDAOS', 'Mindville', 'Sonatype'],
      dtype=object)

In [7]:
# make df with class and text_clean
df = df[['class', 'text_str']]

In [8]:
# Rename text_str to text
df = df.rename(columns={'text_str': 'text'})
df

           class                                               text
0        Highest  We tried upgrading from Spring Boot 2.0.6 to S...
1         Medium  The jobs that appear under Executions section ...
2         Lowest  Working with Spring-XD version 1.3.2.RELEASE\n...
3         Medium  My project 7 node cluster and in that 2 node a...
4            Low  See https://github.com/spring-projects/spring-...
...          ...                                                ...
1404240   Medium                              it is very beautiful.
1404241   Medium                                            library
1404242   Medium  What is reactive-gremlin\r\n\r\nreactive-greml...
1404243   Medium    Android view for a swipeable, weekly calendar.
1404244   Medium  Beetlmvc is a web framework, which can support...

[1404245 rows x 2 columns]

In [9]:
highest = df[df['class'] == 'Highest']
highest["label"] = 1
highest["class_original"] = "Highest"
highest["class"] = "highest"
high = df[df['class'] == 'High']
medium = df[df['class'] == 'Medium']
low = df[df['class'] == 'Low']
lowest = df[df['class'] == 'Lowest']

/tmp/ipykernel_2495553/3737047461.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highest["label"] = 1
/tmp/ipykernel_2495553/3737047461.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highest["class_original"] = "Highest"
/tmp/ipykernel_2495553/3737047461.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  highest["class"] = "highest"

In [10]:
# Concat all class except highest
rest = pd.concat([high, medium, low, lowest])
# Rename class to class_1
rest = rest.rename(columns={'class': 'class_original'})
rest["class"] = "rest" 
rest["label"] = 0
rest

,class_original,text,class,label
7,High,According to the documentation we can load jar...,rest,0
38,High,as stated in https://jira.spring.io/browse/INT...,rest,0
57,High,XD container loose connection with Zookeeper.\...,rest,0
152,High,If I deploy more than one instance of a module...,rest,0
484,High,I am using the POX method to implement a simpl...,rest,0
...,...,...,...,...
1398225,Lowest,Please close this issue - I apologize. Everyth...,rest,0
1401002,Lowest,Following dependencies are not yet ready. I al...,rest,0
1402620,Lowest,"Requesting access to ""org.grails"" to be able t...",rest,0
1403176,Lowest,I'm releasing my artifacts for the first time....,rest,0
1403679,Lowest,"Hi,\r\n\r\nI currently face an unauthorized ex...",rest,0

In [11]:
# Value count rest class
rest['class'].value_counts().to_frame()

         count
class
rest   1348025

In [12]:
from sklearn.utils import shuffle
# Number of rows in the highest class
n_highest = highest.shape[0]

rest_sampled = rest.sample(n=n_highest, random_state=42)  


balanced_data = pd.concat([highest, rest_sampled])

# Shuffle the combined dataset
balanced_data = shuffle(balanced_data, random_state=42)
balanced_data

,class,text,label,class_original
284481,highest,The staging operator metadata ([https://quay.i...,1,Highest
17492,rest,Grails Integration tests that extend grails.pl...,0,Medium
125634,highest,"We must build a JWS 5 image based on UBI 8, us...",1,Highest
1318672,highest,Maven 3.6 was installed via puppet but Tools a...,1,Highest
1284977,highest,We created the state change log in KAFKA-513 w...,1,Highest
...,...,...,...,...
918561,rest,Provide authentication enforcement in ZooKeepe...,0,Medium
56337,rest,in trying to build a framework layer on top of...,0,Medium
1044918,rest,"For the autogenerated ""created"" field, for exa...",0,Low
58230,highest,Adapt WTO to depends on DWO as olm dependency....,1,Highest
281614,highest,When trying unwrap json document from mongo an...,1,Highest

In [13]:
balanced_data['class'].value_counts().to_frame()

         count
class
highest  56220
rest     56220

In [14]:
balanced_data

,class,text,label,class_original
284481,highest,The staging operator metadata ([https://quay.i...,1,Highest
17492,rest,Grails Integration tests that extend grails.pl...,0,Medium
125634,highest,"We must build a JWS 5 image based on UBI 8, us...",1,Highest
1318672,highest,Maven 3.6 was installed via puppet but Tools a...,1,Highest
1284977,highest,We created the state change log in KAFKA-513 w...,1,Highest
...,...,...,...,...
918561,rest,Provide authentication enforcement in ZooKeepe...,0,Medium
56337,rest,in trying to build a framework layer on top of...,0,Medium
1044918,rest,"For the autogenerated ""created"" field, for exa...",0,Low
58230,highest,Adapt WTO to depends on DWO as olm dependency....,1,Highest
281614,highest,When trying unwrap json document from mongo an...,1,Highest

In [15]:
# Count label
balanced_data['label'].value_counts().to_frame()

       count
label
1      56220
0      56220

In [16]:
# Count original class
balanced_data['class_original'].value_counts().to_frame()

                count
class_original
Highest         56220
Medium          39891
Low             11482
High             3441
Lowest           1406

In [17]:
# only keep text and label
balanced_data = balanced_data[['text', 'label']]
balanced_data

                                                      text  label
284481   The staging operator metadata ([https://quay.i...      1
17492    Grails Integration tests that extend grails.pl...      0
125634   We must build a JWS 5 image based on UBI 8, us...      1
1318672  Maven 3.6 was installed via puppet but Tools a...      1
1284977  We created the state change log in KAFKA-513 w...      1
...                                                    ...    ...
918561   Provide authentication enforcement in ZooKeepe...      0
56337    in trying to build a framework layer on top of...      0
1044918  For the autogenerated "created" field, for exa...      0
58230    Adapt WTO to depends on DWO as olm dependency....      1
281614   When trying unwrap json document from mongo an...      1

[112440 rows x 2 columns]

In [18]:
# Save to csv
balanced_data.to_csv('highest_vs_rest_unclean.csv', index=False)

In [19]:
# Read csv
df = pd.read_csv('highest_vs_rest_unclean.csv')
df

                                                     text  label
0       The staging operator metadata ([https://quay.i...      1
1       Grails Integration tests that extend grails.pl...      0
2       We must build a JWS 5 image based on UBI 8, us...      1
3       Maven 3.6 was installed via puppet but Tools a...      1
4       We created the state change log in KAFKA-513 w...      1
...                                                   ...    ...
112435  Provide authentication enforcement in ZooKeepe...      0
112436  in trying to build a framework layer on top of...      0
112437  For the autogenerated "created" field, for exa...      0
112438  Adapt WTO to depends on DWO as olm dependency....      1
112439  When trying unwrap json document from mongo an...      1

[112440 rows x 2 columns]